### ISSUE TITLE
Group Policy .*psm1 Error

### ISSUE THREAD

**Issue by tfromsd** [iadgov/Secure-Host-Baseline#15]
Procedural steps for computer not connected to a domain followed, LGPO.exe file downloaded and extracted as instructed. Please assist or advise how to eliminate ".psm1 521 char:5", ".psm1 522 char 5" ".psm1 709 char 9", etc...
[SHB-ticket.txt](https://github.com/iadgov/Secure-Host-Baseline/files/688118/SHB-ticket.txt)

Text file attached for reference. Thank you.

**Comment by tylerj2050** [comment]
I am having the same identical issue. Let me know how else I can support.

**Comment by iadgovuser1** [comment]
If lgpo.exe isn't located at that relative path, then it won't be found. 

It looks like you are path location is **C:\Users\170admin\Downloads** so that means LGPO would need to be located at **C:\Users\170admin\Downloads\LGPO\LGPO.exe**. If it isn't there, then move it there. 

Otherwise you can change **-ToolPath** to be the full path to where lgpo.exe is located. For example, **-ToolPath 'C:\Users\170admin\Downloads\some folder\lgpo.exe'**

That's my best guess. Let me know if that doesn't work.

**Comment by tfromsd** [comment]
Thank you for the response iadgovuser1. Loaded the full path "...ToolPath 'C:\Users\170admin\Downloads\LGPO\LGPO.exe' and ran the script with no error. Thank you! Going to run an ACAS Scan now on the asset to see what findings display.
