### ISSUE TITLE
STIGs VS SHB

### ISSUE THREAD

**Issue by onedererer** [iadgov/Secure-Host-Baseline#22]
Are the policies contained within the SHB a mirror of the DISA STIGs for those applications/operating system or is there additional development/tweaks that are done? Thank you in advance.

**Comment by iadgovuser1** [comment]
Generally, they are the STIGs but sometimes there may be additional configuration settings included. For example, the IE trusted sites list is configured to trust a bunch of .gov and .mil sites. This is not in the IE STIG, but it is included in the IE GPO for the SHB.

**Comment by onedererer** [comment]
I ask because in a comparison of the **Adobe Acrobat Reader DC Continuous Track STIG - Ver 1, Rel 2** to the SHB policy, I find the below STIG IDs missing

ARDC-CN-000070
ARDC-CN-000115
ARDC-CN-000310
ARDC-CN-000315
ARDC-CN-000325
ARDC-CN-000330
ARDC-CN-000330
ARDC-CN-000340
ARDC-CN-000345

Just checking if this is by design or not.

**Comment by iadgovuser1** [comment]
My quick investigation leads me to believe that they are using the "continuous" version for the install, but are using the "classic" version of the STIG in their GPO. Originally, the SHB Framework developers were using the classic version of Adobe Reader but we got them to switch to the continuous version because of the security benefits. It may be that they never changed their GPO settings from classic to continues. I will bring this up tomorrow during the SHB conference call.

**Comment by iadgovuser1** [comment]
I also just check the latest SHB 10.1 GPOs and they don't provide an Adobe Reader GPO anymore so we will need to provide an updated GPO here.

**Comment by iadgovuser1** [comment]
I'm closing this out since I consider #24 and #25 to be the actual work for this.
