### ISSUE TITLE
Errors: Could not find part of the path to various admx/adml on Server 2016

### ISSUE THREAD

**Issue by JasonFossen** [iadgov/Secure-Host-Baseline#5]
Thanks for the great project!

Command executed which produces errors:

`Invoke-ApplySecureHostBaseline -Path '.\Secure-Host-Baseline' -PolicyNames 'Adobe Reader','AppLocker','Certificates','Chrome','EMET','Internet Explorer','Office 2013','Windows','Windows Firewall' -UpdateTemplates`

Produces 40+ exceptions for various ADMX and ADML file paths similar to:

> Copy-Item : Could not find a part of the path 'C:\Windows\PolicyDefinitions\Office 
> 2013\en-us\access15.adml'.
> At C:\temp\Secure-Host-Baseline\Scripts\GroupPolicy.ps1:1485 char:29
> - ...             Copy-Item -Path $newTemplate -Destination $targetTemplate ...
> -                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
>   - FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.C 
>     opyItemCommand

All of these ADMX/ADML path errors were preceded by this error:

> Import-GPO : The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
> At C:\temp\Secure-Host-Baseline\Scripts\GroupPolicy.ps1:823 char:5
> -     Import-GPO -Path $Path -BackupId $BackupGuid -TargetName $Name -C ...
> -     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Import-GPO], DirectoryNotFoundException
>   - FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.GroupPolicy.Commands. 
>     ImportGpoCommand

Here is the list of ADMX/ADML files not found:

access15.adml
excel15.adml
inf15.adml
lync15.adml
office15.adml
onent15.adml
outlk15.adml
ppt15.adml
proj15.adml
pub15.adml
spd15.adml
visio15.adml
word15.adml
access15.admx
excel15.admx
inf15.admx
lync15.admx
office15.admx
onent15.admx
outlk15.admx
ppt15.admx
proj15.admx
pub15.admx
spd15.admx
visio15.admx
word15.admx
access16.adml
excel16.adml
lync16.adml
office16.adml
onent16.adml
outlk16.adml
ppt16.adml
proj16.adml
pub16.adml
visio16.adml
word16.adml
access16.admx
excel16.admx
lync16.admx
office16.admx
onent16.admx
outlk16.admx
ppt16.admx
proj16.admx
pub16.admx
visio16.admx
word16.admx 

None of the above files are found in these folders:
   .\Secure-Host-Baseline\Windows\Group Policy Templates\
   .\Secure-Host-Baseline\Windows\Group Policy Templates\en-US\

When the -UpdateTemplates switch is not used, the above ADMX/ADML path errors are not thrown, but the Import-GPO errors are still thrown.

My test VM: The eval version of Server 2016 Datacenter with the Desktop Experience, PowerShell 5.1.14393.0, configured as the sole domain controller, logged on as Domain Admin, running PoSh as administrator.

(I suspect the culprit is the [System.Version] test on line 1478 of GroupPolicy.ps1, or maybe the version info in the policy.info files for the GPOs used by the Get-GPODefinitions function, but just guessing, didn't try it out.)

Thanks!

**Comment by iadgovuser1** [comment]
I'm pretty sure I know what the issue is. It is how the policy.json file is structure and where the GPO/GPT folders are located combined with updating $PolicyTemplatePath in Get-GPODefinitions. Easiest fix is going to require changing repo structure for Office and updating the policy.json file. I'm going to want to test this out before committing.

The version test is to prevent updating the PolicyDefinitions folder with admx/adml files from a previous OS release into a newer OS release. In this case Windows Server 2016 has never admx/adml files than what's in the repository. Right now the repo has template files from Windows 10 1511 (plus some templates that were patched) while Windows Server 2016 corresponds to 1607 (well, more like 1609 or 1610). I want to simplify this case and may not even host or update any OS provided templates.    It is safer to stick to the application templates. Still thinking about this.
